---
- name: Get hostname and IP address of Alpine hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Display hostname and IP address
      debug:
        msg: "Hostname: {{ ansible_hostname }}, IP Address: {{ ansible_default_ipv4.address }}"